### ISSUE TITLE
Code style standards

### ISSUE THREAD

**Issue by RecuencoJones** [UNIZAR-30246-WebEngineering/lab1-git-race#26]
I was reviewing the source code in Visual Studio Code and it looks like some source files are indented with 4 spaces and some others with tabs, is there any way we can standardize this across all IDEs?

**Comment by SAReyes** [comment]
Currently the rule for this code smell is inactive in the quality gate, it should be added by an admin in sonarqube.com, this is an issue for @fjlopez.

**Comment by slavcho87** [comment]
I have been reviewing and I think the code is not well organized. Such problems are usually treated in code style guides. Therefore I leave the link of a code style guide AngularJS written by John Papa (Google Software Engineer) https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md. This code guide is about how to write clean code with the MVC scalable architectures. Although this check code style guide for AngularJS how to organize the code can be applied to any type of technology.

**Comment by RecuencoJones** [comment]
@slavcho87 also, there is this [Java code style guide by Google](https://google.github.io/styleguide/javaguide.html)

**Comment by RecuencoJones** [comment]
This might be useful, since it has support in many OS and IDEs http://editorconfig.org/

I think we should set:

- indents with 4 spaces
- use of `lf`
- insert last line at the end of the file
- trim extra whitespaces

**Comment by nebur395** [comment]
Done: #55 
:shipit:

**Comment by SAReyes** [comment]
@nebur395, try not to comment anything that doesn't contribute at all to the discussion, you can reference the issue from your PR if you want some visibility of it.
