### ISSUE TITLE
Refactor all bibliography links

### ISSUE THREAD

**Issue by RecuencoJones** [UNIZAR-30246-WebEngineering/lab1-git-race#30]
Move all bibliography links into their own section in `description.md` with a meaningful link name. For instance:

```
## Bibliography

- [Deploying in Heroku](https://devcenter.heroku.com/articles/deploying-gradle-apps-on-heroku)
```

**Comment by nebur395** [comment]
Done: 6bae8d59e42d5c10de4df6c38022cc9bc7078c64

**Comment by RecuencoJones** [comment]
#33 merged, hence closing the issue, thanks @nebur395!
