### ISSUE TITLE
Log4j2 Integration

### ISSUE THREAD

**Issue by adrianblade** [UNIZAR-30246-WebEngineering/lab1-git-race#41]
It could be interesting integrate log4j2 with your repository.
In the future we could need different logging types
You can get started with:
http://spring-java4dev.com/spring-framework/spring-boot/configure-log4j2-spring-boot

**Comment by nebur395** [comment]
I think it's done: #49

**Comment by fjlopez** [comment]
@adrianblade can you verify if it solves the issue that you raised?
