### ISSUE TITLE
Slack Team

### ISSUE THREAD

**Issue by RecuencoJones** [UNIZAR-30246-WebEngineering/lab1-git-race#47]
I just created [a Slack Team](https://unizar-webeng.slack.com) where we can gather everyone concerned on the subject and receive notifications regarding repos in UNIZAR-30246-WebEngineering.

Please, @fjlopez, join ASAP and invite all the students. Also, you are required to enable the integration of GitHub since we are no admins.

@UNIZAR-30246-WebEngineering/sealteamsix guys, share your emails with @fjlopez for him to invite you too.

**Comment by fjlopez** [comment]
Good idea. I'll do tomorrow (I am at BCN).

**Comment by SAReyes** [comment]
Any news on this? Given the problems on #49 and #50 this is required ASAP.

**Comment by fjlopez** [comment]
I need admin privileges to invite students! I requested it to @RecuencoJones

**Comment by RecuencoJones** [comment]
@fjlopez granted

**Comment by fjlopez** [comment]
Thanks, tomorrow I'll add them.
