### ISSUE TITLE
Dockerize application

### ISSUE THREAD

**Issue by RecuencoJones** [UNIZAR-30246-WebEngineering/lab1-git-race#56]
After reading the discussion regarding #54 I came with the idea of moving the app deployment to docker, this would ease the process of deployment to many platforms that already support docker like Azure or any other cloud service.

**Comment by fjlopez** [comment]
The proposal must include the deployment to one of such platforms as students have the blueprint of a dockerized app as [tutorial](https://github.com/UNIZAR-30246-WebEngineering/tutorials/tree/master/urlshortener-docker).
