### ISSUE TITLE
Requesting merging of the wiki

### ISSUE THREAD

**Issue by deerter** [UNIZAR-30246-WebEngineering/lab1-git-race#66]
I request the owner of the repo to review the changes i made to the wiki and, if correct, please merge them with the current one. I fixed some grammatical errors and added an entry on *SonarQube*.
The link to my repo is https://github.com/deerter/Edited-wiki

Many thanks.

**Comment by RecuencoJones** [comment]
What? Can't you create a pull request to merge the changes? @fjlopez any ideas about this?

**Comment by RecuencoJones** [comment]
Yes, but all I see is that you canged `description.md`, not the wiki itself. 

Let's wait for @fjlopez to reply, but as far as I understand, you should fork this repository, perform the changes you want to do on `description.md`, commit, push to your fork and create a pull request to this repository.

**Comment by RecuencoJones** [comment]
Btw @fjlopez, I think the contents in the section [How to update the Wiki](https://github.com/UNIZAR-30246-WebEngineering/lab1-git-race/blob/master/description.md#how-to-update-the-wiki) are totally misleading for new contributions.

Maybe it would make sense to create a `CONTRIBUTION` template like many other GitHub repos do?

**Comment by fjlopez** [comment]
Yes. It is misleading. I think that it is better to remove it rather than fix.

**Comment by RecuencoJones** [comment]
LGTM

![LGTM](https://lgtm.in/p/6JzE93Exn)
